# -*- mode: ruby -*-
# vi: set ft=ruby :

# CentOS 7 with JDK 7
Vagrant.configure(2) do |config|
  # Builds off of centos-7 box
  config.vm.box = "esamson/centos-7"
  config.vm.box_url = "https://github.com/esamson/baseboxes/releases/download/centos-7-v3/package.box"

  config.vm.provider "virtualbox" do |vbox|
      vbox.name = "jdk-7"
  end

  # Install JDK 7
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /opt/jdk-7
    tar -x -f /vagrant/.deps/jdk-7.tar.gz -C /opt/jdk-7 --strip-components=1
    cp /vagrant/etc/profile.d/java.sh /etc/profile.d/java.sh 
  SHELL

  config.vm.provision "file",
      source: "../scripts/free-up-disk.sh",
      destination: "free-up-disk.sh"

end
